name: Java CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Ensure gradlew has execute permissions
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the project
      - name: Build the project
        run: ./gradlew build

      # Run tests locally
      - name: Run tests
        run: ./gradlew test

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-java-app .

      # Run Docker container
      - name: Run Docker container
        run: |
          docker run -d --name my-java-app-container my-java-app
          sleep 5  # Wait for the container to start

      # Check if the Docker container is running
      - name: Verify Docker container status
        run: |
          docker ps --filter "name=my-java-app-container" --filter "status=running" --format "{{.Names}}" | grep -w "my-java-app-container"

      # Run tests inside Docker container
      - name: Run tests in Docker container
        run: |
          docker exec my-java-app-container ./gradlew test

      # Stop and remove the container
      - name: Stop and remove Docker container
        run: |
          docker stop my-java-app-container
          docker rm my-java-app-container
